### ISSUE TITLE
Verify proper handling of various files

### ISSUE THREAD

**Issue by nvs** [nvs/map#64]
Basically, verify any differences in the formats of these files for the following patches. And also see if there is information not currently being handled.

## 1.31
- [x] `war3map.w3a` (and `w3b`, `w3d`, `w3h`, `w3q`, `w3t`, `w3u`)
    Nothing seems to have changed.
- [x] `war3map.w3o`
    Nothing seems to have changed.
- [x] `war3map.wts`
    Nothing seems to have changed.
- [x] `*.ini` (e.g. the interface and gameplay constants)
    Nothing seems to have changed.
- [x] `war3map.imp`
    Fresh imports have a value of `0x15` on their first save of the map. On subsequent saves for the same import this value does not change.

## 1.32 (Reforged)
- [x] `war3map.w3a` (and `w3b`, `w3d`, `w3h`, `w3q`, `w3t`, `w3u`)
    Nothing seems to have changed.
- [x] `war3map.w3o`
    Nothing seems to have changed.
- [x] `war3map.wts`
    Nothing seems to have changed.
- [x] `*.ini` (e.g. the interface and gameplay constants)
    Nothing seems to have changed.
- [x] `war3map.imp`
    Fresh imports have a value of `0x15` on their first save of the map. On subsequent saves for the same import this value becomes `0x1D`.

## To-do
- [x] `war3map.w3a` (and `w3b`, `w3d`, `w3h`, `w3q`, `w3t`, `w3u`)
    Store the version used for each file? Currently, the value is unpacked. And on packing it is assumed to equal `2`. Can address this later if needed. Assuming the format ever changes.
- [x] `war3map.wts`
    ~~Preserve comments?~~ The ones generated by the WE can be useful in identifying the string. Need to verify that the game identifies trigger strings in a custom `war3map.lua`. If it does not, it may replace (or remove) them as it sees fit. This could prevent properly saving the map in the WE without breaking trigger strings. Then again, it does not properly save since 1.31 anyway as the map's script gets overwritten.

    Not much sense in preserving the comments. Also, it was decided that support for saving the map in the WE will not be added or addressed. If someone using Map does want support for multiple locales with the `war3map.wts`, they will just need to manage that on their own within build files passed to Map.
- [x] `war3map.imp`
    Generate an imports file that matches a target patch? ~~For 1.32 support, simplify handling of locales and HD/SD?~~ Examples of paths used:
    ```
    war3imported\test.txt
    _Locales\enUS.war3mod\war3imported\test.txt -- enUS
    _Locales\esES.war3mod\war3imported\test.txt -- esES
    _HD.w3mod\war3imported\test.txt -- HD
    _HD.w3mod\_Locales\enUS.war3mod\war3imported\test.txt -- HD, enUS
    _HD.w3mod\_Locales\esES.war3mod\war3imported\test.txt -- HD, esES
    ```
    Of note is that the `_Locales` folder and all locales exists for freshly created maps. However, folders for their HD counterparts are not automatically created. As far as simplifying things, this is not necessary. No sense adding more complexity where it is not needed.

    So just adjust the byte before the path for each file as needed. For 1.32, this will be `0x1D`. And for 1.31, this will be `0x15`.
